[book]
authors = ["onlytiancai"]
language = "zh-cn"
src = "src"
title = "The Little Book of Linear Algebra"
[preprocessor.katex]
after = ["links"]
no-css = true
[output.html.search]
enable = false
[output.html.print]
enable = false
[output.html]
additional-css = ["katex.min.css"]

