[book]
authors = ["onlytiancai"]
language = "zh-cn"
src = "src"
title = "The Little Book of Linear Algebra"
[preprocessor.katex]
after = ["links"]
[output.html.search]
enable = false
[output.html.print]
enable = false

